# Generated by Django 4.2.2 on 2023-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_appointment_patient_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
