# Generated by Django 4.2.1 on 2023-06-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_depertment_alter_doctors_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depertment',
            new_name='Department',
        ),
    ]
