# Generated by Django 4.2.1 on 2023-06-05 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0002_doctors_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': False, 'is_superadmin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slots',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True, 'is_superadmin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
