# Generated by Django 4.2.1 on 2023-06-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_rename_depertment_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='desciption',
            new_name='description',
        ),
    ]
