# Generated by Django 4.2.2 on 2023-06-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0009_alter_doctors_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
