# Generated by Django 4.2.2 on 2023-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0010_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
